# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: debug-statements

-   repo: https://github.com/lk16/detect-missing-init
    rev: v0.1.6
    hooks:
    -   id: detect-missing-init
        args: [
            "--create",
            "--track",
            "--python-folders",
            "src/datarobot_genai",
            "--python-folders",
            "tests",
        ]

-   repo: https://github.com/asottile/pyupgrade
    rev: v3.21.0
    hooks:
    -   id: pyupgrade

-   repo: local
    hooks:
    -   id: ruff-format
        name: ruff-format
        entry: task fix-ruff-format
        language: system
        types: [ python ]
        pass_filenames: false
    -   id: ruff
        name: ruff
        entry: task fix-ruff
        language: system
        types: [ python ]
        require_serial: true
        pass_filenames: false
    -   id: mypy
        name: mypy
        entry: task mypy
        language: system
        types: [ python ]
        require_serial: true
        pass_filenames: false
    -   id: ruff-format-e2e
        name: ruff-format-e2e
        entry: cd e2e-tests && task fix-ruff-format
        language: system
        types: [ python ]
        pass_filenames: false
    -   id: ruff-e2e
        name: ruff-e2e
        entry: cd e2e-tests && task fix-ruff
        language: system
        types: [ python ]
        require_serial: true
        pass_filenames: false
    -   id: mypy-e2e
        name: mypy-e2e
        entry: cd e2e-tests && task mypy
        language: system
        types: [ python ]
        require_serial: true
        pass_filenames: false
    -   id: fix-licenses
        name: fix-licenses
        entry: task fix-licenses-files --
        language: system
        require_serial: true
        pass_filenames: true
    -   id: version-check-and-bump
        name: version-check-and-bump (PyPI)
        entry: uv run --no-sync python scripts/check_and_bump_version.py --repo pypi --bump patch --apply
        language: system
        pass_filenames: false
        stages: [ pre-commit ]
