name: Mark PR as Reviewed

on:
  pull_request_review:
    types: [submitted]

jobs:
  mark-reviewed:
    if: github.event.review.state == 'approved'
    uses: datarobot-oss/github-actions/.github/workflows/mark-pr-reviewed.yaml@0.0.3
    with:
      pr_number: ${{ github.event.pull_request.number }}
